# Generated by Django 4.2.6 on 2023-10-24 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankbranch',
            options={},
        ),
    ]
