# Generated by Django 4.2.6 on 2023-10-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_bankbranch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankbranch',
            options={'managed': False},
        ),
    ]
